package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import pfa.model.dossier.Avis;
import pfa.model.dossier.Dossier;
import pfa.model.dossier.Dpetl;
import pfa.model.dossier.LettreAppro;
import pfa.model.dossier.Nature;
import pfa.model.dossier.Note;
import pfa.model.users.Utilisateur;




/**
 * DossierCpsEtude generated by hbm2java
 */
@Entity
@Table(name = "dossier_cps_etude")
@Inheritance(strategy = InheritanceType.JOINED)
public class DossierCpsEtude extends DossierCps implements java.io.Serializable {


    //**************************************************************************************//       
    //**************************************************************************************//
    @OneToOne(mappedBy = "dossierCpsEtude")
    @Cascade({CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
    private DossierCpsTravaux dossierCpsTravaux;

    //**************************************************************************************//       
    //**************************************************************************************//
    public DossierCpsEtude() {
    }

    public DossierCpsEtude(DossierCpsTravaux dossierCpsTravaux, String dossier, Date dateEntree, Date dateSortie, String refAppro, String programmation, Date dateCreation, List<Note> notes, LettreAppro lettreAppro, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, dateSortie, refAppro, programmation, dateCreation, notes, lettreAppro, avis, dpetl, nature);
        this.dossierCpsTravaux = dossierCpsTravaux;
    }

    public DossierCpsEtude(DossierCpsTravaux dossierCpsTravaux, String dossier, Date dateEntree, String refAppro, String programmation, Date dateCreation, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, refAppro, programmation, dateCreation, avis, dpetl, nature);
        this.dossierCpsTravaux = dossierCpsTravaux;
    }

    

    //**************************************************************************************//       
    //**************************************************************************************//

    public DossierCpsTravaux getDossierCpsTravaux() {
        return dossierCpsTravaux;
    }

    public void setDossierCpsTravaux(DossierCpsTravaux dossierCpsTravaux) {
        this.dossierCpsTravaux = dossierCpsTravaux;
    }
    
    //**************************************************************************************//       
    //**************************************************************************************//

}


