package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import pfa.model.users.Utilisateur;




/**
 * DossierLiaison generated by hbm2java
 */
@Entity
@Table(name = "dossier_liaison")
public class DossierLiaison extends Dossier implements java.io.Serializable {

    @ManyToOne(optional = true)
    @Cascade({CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
    @JoinColumn(name = "id_phase",nullable = false)
     private Phase phase;
     @Column(length = 500)
     private String route;
     private Double longueur;
     private Double pkdebut;
     private Double pkfin;
     private String bet;
     
    //**************************************************************************************//       
    //**************************************************************************************//
    public DossierLiaison(){
    }

    public DossierLiaison(Phase phase, String route, Double longueur, Double pkdebut, Double pkfin, String bet) {
        this.phase = phase;
        this.route = route;
        this.longueur = longueur;
        this.pkdebut = pkdebut;
        this.pkfin = pkfin;
        this.bet = bet;
    }

    public DossierLiaison(Phase phase, String route, Double longueur, Double pkdebut, Double pkfin, String bet, String dossier, Date dateEntree, Date dateSortie, String refAppro, String programmation, Date dateCreation, List<Note> notes, LettreAppro lettreAppro, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, dateSortie, refAppro, programmation, dateCreation, notes, lettreAppro, avis, dpetl, nature);
        this.phase = phase;
        this.route = route;
        this.longueur = longueur;
        this.pkdebut = pkdebut;
        this.pkfin = pkfin;
        this.bet = bet;
    }

    public DossierLiaison(Phase phase, String route, Double longueur, Double pkdebut, Double pkfin, String bet, String dossier, Date dateEntree, String refAppro, String programmation, Date dateCreation, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, refAppro, programmation, dateCreation, avis, dpetl, nature);
        this.phase = phase;
        this.route = route;
        this.longueur = longueur;
        this.pkdebut = pkdebut;
        this.pkfin = pkfin;
        this.bet = bet;
    }






    //**************************************************************************************//       
    //**************************************************************************************//
    public Phase getPhase() {
        return this.phase;
    }
    
    public void setPhase(Phase phase) {
        this.phase = phase;
    }

    public String getBet() {
        return this.bet;
    }
    
    public void setBet(String bet) {
        this.bet = bet;
    }

    //**************************************************************************************//       
    //**************************************************************************************//

    public String getRoute() {
        return route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public Double getLongueur() {
        return longueur;
    }

    public void setLongueur(Double longueur) {
        this.longueur = longueur;
    }

    public Double getPkdebut() {
        return pkdebut;
    }

    public void setPkdebut(Double pkdebut) {
        this.pkdebut = pkdebut;
    }

    public Double getPkfin() {
        return pkfin;
    }

    public void setPkfin(Double pkfin) {
        this.pkfin = pkfin;
    }



}


