package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import pfa.model.users.Utilisateur;




/**
 * DossierCpsTravaux generated by hbm2java
 */
@Entity
@Table(name = "dossier_cps_travaux")
@Inheritance(strategy = InheritanceType.JOINED)
public class DossierCpsTravaux  extends DossierCps implements java.io.Serializable {

    //**************************************************************************************//       
    //**************************************************************************************//

    @OneToOne(optional = false)
    @Cascade({CascadeType.MERGE,CascadeType.SAVE_UPDATE,CascadeType.REFRESH})
    @JoinColumn(name = "cps_etude",unique = true)
    private DossierCpsEtude dossierCpsEtude;
    
    @OneToOne(mappedBy = "dossierCpsTravaux",optional = true)
    @Cascade({CascadeType.MERGE,CascadeType.SAVE_UPDATE,CascadeType.PERSIST})
    private DossierCpsControle dossierCpsControle;

    //**************************************************************************************//       
    //**************************************************************************************//

    public DossierCpsTravaux() {
    }

    public DossierCpsTravaux(DossierCpsEtude dossierCpsEtude, String dossier, Date dateEntree, Date dateSortie, String refAppro, String programmation, Date dateCreation, List<Note> notes, LettreAppro lettreAppro, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, dateSortie, refAppro, programmation, dateCreation, notes, lettreAppro, avis, dpetl, nature);
        this.dossierCpsEtude = dossierCpsEtude;
    }

    public DossierCpsTravaux(DossierCpsEtude dossierCpsEtude, String dossier, Date dateEntree, String refAppro, String programmation, Date dateCreation, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, refAppro, programmation, dateCreation, avis, dpetl, nature);
        this.dossierCpsEtude = dossierCpsEtude;
    }

    
    

    //**************************************************************************************//       
    //**************************************************************************************//

    public DossierCpsEtude getDossierCpsEtude() {
        return dossierCpsEtude;
    }

    public void setDossierCpsEtude(DossierCpsEtude dossierCpsEtude) {
        this.dossierCpsEtude = dossierCpsEtude;
    }
    

    public DossierCpsControle getDossierCpsControle() {
        return dossierCpsControle;
    }

    public void setDossierCpsControle(DossierCpsControle dossierCpsControle) {
        this.dossierCpsControle = dossierCpsControle;
    }
    //**************************************************************************************//       
    //**************************************************************************************//
}


