package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import pfa.model.dossier.Avis;
import pfa.model.dossier.Dossier;
import pfa.model.dossier.Dpetl;
import pfa.model.dossier.LettreAppro;
import pfa.model.dossier.Nature;
import pfa.model.dossier.Note;
import pfa.model.users.Utilisateur;




/**
 * DossierCpsControle generated by hbm2java
 */
@Entity
@Table(name = "dossier_cps_controle")
public class DossierCpsControle extends DossierCps implements java.io.Serializable {
    
    
    @OneToOne(optional = false)
    @Cascade({CascadeType.MERGE,CascadeType.SAVE_UPDATE,CascadeType.REFRESH})
    @JoinColumn(name = "cps_travaux",unique = false)
    private DossierCpsTravaux dossierCpsTravaux;

    //**************************************************************************************//
    //**************************************************************************************//
    public DossierCpsControle() {
    }

    public DossierCpsControle(DossierCpsTravaux dossierCpsTravaux, String dossier, Date dateEntree, Date dateSortie, String refAppro, String programmation, Date dateCreation, List<Note> notes, LettreAppro lettreAppro, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, dateSortie, refAppro, programmation, dateCreation, notes, lettreAppro, avis, dpetl, nature);
        this.dossierCpsTravaux = dossierCpsTravaux;
    }

    public DossierCpsControle(DossierCpsTravaux dossierCpsTravaux, String dossier, Date dateEntree, String refAppro, String programmation, Date dateCreation, Avis avis, Dpetl dpetl, Nature nature) {
        super(dossier, dateEntree, refAppro, programmation, dateCreation, avis, dpetl, nature);
        this.dossierCpsTravaux = dossierCpsTravaux;
    }


    //**************************************************************************************//       
    //**************************************************************************************//

    public DossierCpsTravaux getDossierCpsTravaux(){
        return this.dossierCpsTravaux;
    }
    

    public void setDossierCpsTravaux(DossierCpsTravaux dossierCpsTravaux) {
        this.dossierCpsTravaux = dossierCpsTravaux;
    }
    //**************************************************************************************//       
    //**************************************************************************************//

}


