package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import com.sun.org.apache.bcel.internal.generic.D2F;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.*;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.CascadeType;
/**
 * Dpetl generated by hbm2java
 */
@Entity
@Table(name = "dpetl")
public class Dpetl  implements java.io.Serializable {

    @Id
    @Column(name = "id_dpetl",insertable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idDpetl;
     private String libele;
     
     @OneToMany(mappedBy = "dpetl")
     @Cascade({CascadeType.PERSIST,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
     private List<Dossier> dossiers = new ArrayList<Dossier>();
    //**************************************************************************************//       
    //**************************************************************************************//

    public Dpetl() {
    }

    public Dpetl(String libele) {
        this.libele = libele;
    }

    public Dpetl(String libele,ArrayList<Dossier> dossiers) {
        this.dossiers = dossiers;
        this.libele = libele;
    }
    
    //**************************************************************************************//       
    //**************************************************************************************//
    public Integer getIdDpetl() {
        return this.idDpetl;
    }
    
    public void setIdDpetl(Integer idDpetl) {
        this.idDpetl = idDpetl;
    }
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }

    public ArrayList<Dossier> getDossiers() {
        return (ArrayList<Dossier>) dossiers;
    }

    public void setDossiers(List<Dossier> dossiers) {
        this.dossiers = (ArrayList<Dossier>)dossiers;
    }
   //**************************************************************************************//       
    //**************************************************************************************//
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + (this.idDpetl != null ? this.idDpetl.hashCode() : 0);
        hash = 53 * hash + (this.libele != null ? this.libele.hashCode() : 0);
        return hash;
    }
   //**************************************************************************************//       
    //**************************************************************************************//
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Dpetl other = (Dpetl) obj;
        if (this.idDpetl != other.idDpetl && (this.idDpetl == null || !this.idDpetl.equals(other.idDpetl))) {
            return false;
        }
        if ((this.libele == null) ? (other.libele != null) : !this.libele.equals(other.libele)) {
            return false;
        }
        return true;
    }
   //**************************************************************************************//       
    //**************************************************************************************//
    @Override
    public String toString() {
        return libele;
    }
}


