package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import pfa.model.users.Utilisateur;

/**
 * LettreAppro generated by hbm2java
 */
@Entity
@Table(name = "lettre_appro")
public class LettreAppro  implements java.io.Serializable {


     @Id
     @OneToOne(optional = false)
     @Cascade(value = {CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
     @JoinColumn(name = "id_lettre_appro")
     private Dossier dossier;
     
     @ManyToOne(optional = false)
     @Cascade(value = {CascadeType.MERGE,CascadeType.REFRESH,CascadeType.PERSIST,CascadeType.SAVE_UPDATE})
     @JoinColumn(name = "matricule_utilisateur")
     private Utilisateur utilisateur;
     
     private String lien;
     
     @Temporal(TemporalType.DATE)
     private Date dateCreation;
    //**************************************************************************************//       
    //**************************************************************************************//
    public LettreAppro() {
    }

    public LettreAppro(Dossier dossier, Utilisateur utilisateur, Date dateCreation) {
        this.dossier = dossier;
        this.utilisateur = utilisateur;
        this.dateCreation = dateCreation;
    }
    public LettreAppro(Dossier dossier, Utilisateur utilisateur, String lien, Date dateCreation) {
       this.dossier = dossier;
       this.utilisateur = utilisateur;
       this.lien = lien;
       this.dateCreation = dateCreation;
    }
    //**************************************************************************************//       
    //**************************************************************************************//

    public Dossier getDossier() {
        return this.dossier;
    }
    
    public void setDossier(Dossier dossier) {
        this.dossier = dossier;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getLien() {
        return this.lien;
    }
    
    public void setLien(String lien) {
        this.lien = lien;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    //**************************************************************************************//       
    //**************************************************************************************//



}


