package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1



import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cascade;

/**
 * Nature generated by hbm2java
 */
@Entity
@Table(name = "nature")
public class Nature  implements java.io.Serializable {

    //**************************************************************************************//       
    //**************************************************************************************//
    @Id
    @Column(name = "id_nature",insertable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idNature;
     private String libele;
     @OneToMany(mappedBy = "dpetl")
     @Cascade(value = {CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
     private List<Dossier> dossiers = new ArrayList<Dossier>();
    //**************************************************************************************//       
    //**************************************************************************************//
    public Nature() {
    }

	
    public Nature(String libele) {
        this.libele = libele;
    }
    public Nature(String libele, List<Dossier> dossiers) {
       this.libele = libele;
       this.dossiers = dossiers;
    }
    //**************************************************************************************//       
    //**************************************************************************************// 
    public Integer getIdNature() {
        return this.idNature;
    }
    
    public void setIdNature(Integer idNature) {
        this.idNature = idNature;
    }
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }
    public ArrayList<Dossier> getDossiers() {
        return (ArrayList<Dossier>) this.dossiers;
    }
    
    public void setDossiers(List<Dossier> dossiers) {
        this.dossiers = dossiers;
    }
    //**************************************************************************************//       
    //**************************************************************************************//
    @Override
    public String toString() {
        return libele;
    }



}


