package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import pfa.model.users.Utilisateur;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note")
public class Note  implements java.io.Serializable {
    //**************************************************************************************//       
    //**************************************************************************************//
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id_note")
     private Integer idNote;
     
     @ManyToOne(optional = false)
     @Cascade(value = {CascadeType.MERGE,CascadeType.REFRESH,CascadeType.PERSIST,CascadeType.SAVE_UPDATE})

     @JoinColumn(name = "id_dossier",nullable = false)
     private Dossier dossier;
     
     @ManyToOne(optional = false)
     @JoinColumn(name = "utilisateur",nullable = false)
     private Utilisateur utilisateur;
     
     
     private String note;
     
     @Column(name = "lien",unique = true)
     private String lien;
     
     @Column(name = "date_creation",nullable = true)
     @Temporal(TemporalType.DATE)
     private Date dateCreation;
    //**************************************************************************************//       
    //**************************************************************************************//

    public Note() {
    }

    public Note(Dossier dossier, Utilisateur utilisateur, String note, String lien, Date dateCreation) {
        this.dossier = dossier;
        this.utilisateur = utilisateur;
        this.note = note;
        this.lien = lien;
        this.dateCreation = dateCreation;
    }

    public Note(Dossier dossier, Utilisateur utilisateur, String lien, Date dateCreation) {
        this.dossier = dossier;
        this.utilisateur = utilisateur;
        this.lien = lien;
        this.dateCreation = dateCreation;
    }
    //**************************************************************************************//       
    //**************************************************************************************//
    public Integer getIdNote() {
        return this.idNote;
    }
    
    public void setIdNote(Integer idNote) {
        this.idNote = idNote;
    }
    public Dossier getDossier() {
        return this.dossier;
    }
    
    public void setDossier(Dossier dossier) {
        this.dossier = dossier;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getLien() {
        return this.lien;
    }
    
    public void setLien(String lien) {
        this.lien = lien;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    
    //**************************************************************************************//       
    //**************************************************************************************//



}


