package pfa.model.dossier;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Phase generated by hbm2java
 */
@Entity
@Table(name = "phase")
public class Phase  implements java.io.Serializable {

    //**************************************************************************************//       
    //**************************************************************************************//
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id_phase")
     private Integer idPhase;
     @Column(unique = true)
     private String libele;
     @OneToMany(mappedBy = "phase")
     @Cascade(value = {CascadeType.REFRESH,CascadeType.PERSIST,CascadeType.SAVE_UPDATE})
     private List<DossierLiaison> dossierLiaisons = new ArrayList<DossierLiaison>();
    //**************************************************************************************//       
    //**************************************************************************************//
    public Phase(String libele) {
        this.libele = libele;
    }

    public Phase() {
    }


    //**************************************************************************************//       
    //**************************************************************************************//
    public Integer getIdPhase() {
        return this.idPhase;
    }
    
    public void setIdPhase(Integer idPhase) {
        this.idPhase = idPhase;
    }
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }


    public List<DossierLiaison> getDossierLiaisons() {
        return dossierLiaisons;
    }

    public void setDossierLiaisons(List<DossierLiaison> dossierLiaisons) {
        this.dossierLiaisons = dossierLiaisons;
    }

    public static List<Phase> getPhases(){
        List<Phase> allps = new ArrayList<Phase>();
        allps.add(new Phase("Phase 1"));
        allps.add(new Phase("Phase 2"));
        allps.add(new Phase("Phase 3"));
        allps.add(new Phase("Phase 4"));
        return allps;
    }
    //**************************************************************************************//       
    //**************************************************************************************//
    @Override
    public String toString() {
        return libele;
    }
}


