package pfa.model.archivage;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
/**
 * ColonneArchivage generated by hbm2java
 */
@Entity
@Table(name = "colonne")
public class ColonneArchivage  implements java.io.Serializable {
    //**************************************************************************************//     
    //**************************************************************************************//  
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_colonne")
     private Integer idColonne;
    @ManyToOne(optional = false)
    @JoinColumn(name = "id_ligne",nullable = false)
     private LigneArchivage ligneArchivage;
    @Column(name = "numero_colonne")
    private int numColonne;
    @OneToMany(mappedBy = "colonneArchivage")
    @Cascade({CascadeType.PERSIST,CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
    private List<Archive> archives;
    //**************************************************************************************//     
    //**************************************************************************************//  



    //**************************************************************************************//     
    //**************************************************************************************//  
    public Integer getIdColonne() {
        return this.idColonne;
    }
    
    public void setIdColonne(Integer idColonne) {
        this.idColonne = idColonne;
    }
    public LigneArchivage getLigneArchivage() {
        return this.ligneArchivage;
    }
    
    public void setLigneArchivage(LigneArchivage ligneArchivage) {
        this.ligneArchivage = ligneArchivage;
    }
    public int getNumColonne() {
        return this.numColonne;
    }
    
    public void setNumColonne(int numColonne) {
        this.numColonne = numColonne;
    }


    //**************************************************************************************//     
    //**************************************************************************************//  

    public List<Archive> getArchives() {
        return archives;
    }

    public void setArchives(List<Archive> archives) {
        this.archives = archives;
    }
}


