package pfa.model.archivage;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.ManyToAny;

/**
 * LigneArchivage generated by hbm2java
 */
@Entity
@Table(name = "ligne_archivage")
public class LigneArchivage  implements java.io.Serializable {
    //**************************************************************************************//     
    //**************************************************************************************//  
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_ligne")
     private Integer idLigne;
    
     @ManyToOne(optional = false)
     @JoinColumn(name = "id_range",nullable = false)
     private RangeArchivage rangeArchivage;
     
     @Column(name = "numero_ligne")
     private int numLigne;
     
     @OneToMany(mappedBy = "ligneArchivage")
     @Cascade({CascadeType.PERSIST,CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
     private List<ColonneArchivage> colonneArchivages = new ArrayList<ColonneArchivage>();
    //**************************************************************************************//     
    //**************************************************************************************//  
    public LigneArchivage() {
    }	
    public LigneArchivage(RangeArchivage rangeArchivage, int numLigne) {
        this.rangeArchivage = rangeArchivage;
        this.numLigne = numLigne;
    }
    public LigneArchivage(RangeArchivage rangeArchivage, int numLigne, ArrayList<ColonneArchivage> colonneArchivages) {
       this.rangeArchivage = rangeArchivage;
       this.numLigne = numLigne;
       //this.colonneArchivages = colonneArchivages;
    }
    //**************************************************************************************//     
    //**************************************************************************************//  
    public Integer getIdLigne() {
        return this.idLigne;
    }
    
    public void setIdLigne(Integer idLigne) {
        this.idLigne = idLigne;
    }
    public RangeArchivage getRangeArchivage() {
        return this.rangeArchivage;
    }
    
    public void setRangeArchivage(RangeArchivage rangeArchivage) {
        this.rangeArchivage = rangeArchivage;
    }
    public int getNumLigne() {
        return this.numLigne;
    }
    
    public void setNumLigne(int numLigne) {
        this.numLigne = numLigne;
    }

    //**************************************************************************************//     
    //**************************************************************************************//  

    public List<ColonneArchivage> getColonneArchivages() {
        return colonneArchivages;
    }

    public void setColonneArchivages(List<ColonneArchivage> colonneArchivages) {
        this.colonneArchivages = colonneArchivages;
    }

}


