package pfa.model.archivage;
// Generated 23 avr. 2016 02:24:37 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import org.hibernate.annotations.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;

/**
 * RangeArchivage generated by hbm2java
 */
@Entity
@Table(name = "range_archivage")
public class RangeArchivage  implements java.io.Serializable {
    //**************************************************************************************//     
    //**************************************************************************************//  
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_range")
     private Integer idRange;
    @Column(name = "numero_range")
    private int numRange;
    @OneToMany(mappedBy = "rangeArchivage")
    @Cascade({CascadeType.PERSIST,CascadeType.MERGE,CascadeType.REFRESH,CascadeType.SAVE_UPDATE})
    private List<LigneArchivage> ligneArchivages = new ArrayList<LigneArchivage>();

    public RangeArchivage() {
    }
    //**************************************************************************************//     
    //**************************************************************************************//  
    public RangeArchivage(int numRange) {
        this.numRange = numRange;
    }
    public RangeArchivage(int numRange, ArrayList<LigneArchivage> ligneArchivages) {
       this.numRange = numRange;
       this.ligneArchivages = ligneArchivages;
    }
    //**************************************************************************************//     
    //**************************************************************************************//  
    public Integer getIdRange() {
        return this.idRange;
    }
    
    public void setIdRange(Integer idRange) {
        this.idRange = idRange;
    }
    public int getNumRange() {
        return this.numRange;
    }
    
    public void setNumRange(int numRange) {
        this.numRange = numRange;
    }
    public List<LigneArchivage> getLigneArchivages() {
        return this.ligneArchivages;
    }
    
    public void setLigneArchivages(List<LigneArchivage> ligneArchivages) {
        this.ligneArchivages = ligneArchivages;
    }
    
    //**************************************************************************************//     
    //**************************************************************************************//  


}


